### PR TITLE
Fix some panic areas

### PR DESCRIPTION
**Pull request by scd31**
I was messing around with a fuzzer and found a few areas that could panic with the wrong input. After making these changes, the fuzzer can't find any more issues.

I don't understand the LDPC algorithm at all, so it would be good to be extra careful when reviewing. The unit tests in this project + in my own project are still passing, so I didn't completely break anything, at least.

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Thank you, I appreciate you spending the time to fuzz it and report back! The changes look sensible, don't measurably affect the benchmark times, and I'm confident they won't affect the decoding except where previously it might have panicked or wrapped incorrectly anyway.

**Comment by adamgreig** [comment]
I'm happy to cut a new release any time, but if you might have other changes coming I'll hold off. Let me know when you'd like a release.

**Comment by scd31** [comment]
I was thinking of adding a `hard_bit()` method to the `DecodeFrom` trait, which returns a bool (basically if above 0, it's a 1, otherwise it's a 0). We'd get this for free without having to implement it on every type. Thoughts?

**Comment by adamgreig** [comment]
Sounds reasonably, presumably with a default implementation of `*self < Self::zero()`?

Where would you use `hard_bit()`? There's a bunch of comparisons to `T::zero()` in `decode_ms()` which I think could be replaced, and the `llrs_to_hard()` method. I'm a little concerned that currently most comparisons are `<` (or compatibly `>=`), but a few are `<=`. Seven years on, I can't say for sure if that was deliberate, but I'm sure changing it would have a small impact on decoding performance.

**Comment by scd31** [comment]
My reason for adding it was for external use actually. For my use case I need to convert to hard bits for detecting sync words, and then the actual LDPC decoding is done using the soft bits. I figured that's a semi-common thing to do. I wasn't going to touch the internals of the library beyond adding that method.

**Comment by adamgreig** [comment]
Ah, OK! Could you use the existing `llrs_to_hard()` method or do you specifically want to process bit-by-bit? Anyway, no issue adding it, and we could then use it internally to simplify some of those comparisons.

**Comment by scd31** [comment]
Theoretically I could, although it requires picking a specific `LDPCCode` and it has an assertion that `N` matches. I'll go ahead and add those methods, and maybe in the future it would be good to update that method to make it a bit more general. Thanks!

**Pull request merged**
